management:
  endpoints:
    web:
      base-path: /manage
      expose: "*"

server:
  servlet:
    context-path: /v1
  port: 8119

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

commentx:
  couchbase:
    bootstrap-hosts:
    - localhost
    bucket:
      name: default
      password: ""
      persist-factor: one
    sslEnabled: false
    connectionTimeout: 1000
    keystorePath: "{user.home}/.keystore"
    keystorePassword: "xxxxx"
